// Maps Storybook story IDs to the component + resolved args that the story renders.
// Docusaurus renders the component directly, removing the need for an external iframe.
// When story args change in Button.stories.tsx, this registry updates automatically.

import { type ComponentType, type ReactElement } from 'react';
import Button from '../components/Button/BtnIcon';
import type { BtnIconProps as ButtonProps } from '../components/Button/BtnIcon';
import {
  BasicIconButtonExample,
  IconButtonGroupExample,
  IconButtonSizesExample,
  IconButtonStatesExample,
  IconButtonVariantsExample,
} from './IconButtonExamples';
import {
  BasicSplitButtonExample,
  SplitButtonMenuExample,
  SplitButtonSizesExample,
  SplitButtonStatesExample,
  SplitButtonWithIconExample,
} from './SplitButtonExamples';
import {BasicSegmentedControlExample} from './SegmentedControlExamples';
import {
  BasicToggleButtonExample,
  ToggleButtonWithBadgeExample,
  ToggleButtonGroupExample,
  ToggleButtonSizesExample,
  ToggleButtonStatesExample,
} from './ToggleButtonExamples';
import {
  BasicAccordionExample,
  AccordionExpandedExample,
  AccordionSelectableExample,
  AccordionWithDividerExample,
  AccordionSizesExample,
} from './AccordionExamples';
import {
  BasicCardExample,
  CardHorizontalExample,
  CardStatesExample,
  CardWithoutImageExample,
} from './CardExamples';
import {
  AvatarDropdownExample,
  CheckboxDropdownExample,
  DefaultDropdownExample,
  DropdownStateExample,
  FlagDropdownExample,
  GroupedDropdownExample,
} from './DropdownExamples';
import {
  BasicTreeMenuExample,
  DisabledTreeMenuExample,
  ExpandedCollapsedTreeMenuExample,
  SelectableTreeMenuExample,
  TreeMenuWithCountExample,
  TreeMenuWithLeadingIconExample,
} from './TreeMenuExamples';
import {
  BasicTableExample,
  BasicTableTreeExample,
  ExpandedTableTreeExample,
  MetadataToolbarExample,
  MultiLevelHierarchyExample,
  SelectableTableExample,
  TableTreeWithBadgeExample,
  TableTreeWithSelectedRowExample,
  TableWithFixedActionColumnExample,
  TableWithPaginationExample,
  TableWithStatusExample,
  ToolbarWithActionsExample,
  ToolbarWithColumnVisibilityExample,
  ToolbarWithSearchExample,
  ToolbarWithTableExample,
} from './DataTableExamples';
import {
  BasicCheckboxExample,
  BasicRadioExample,
  BasicSwitchExample,
  CheckboxControlGroupExample,
  CheckboxGroupExample,
  CheckboxWithDescriptionExample,
  ControlGroupWithDescriptionExample,
  DisabledCheckboxExample,
  DisabledRadioExample,
  DisabledSwitchExample,
  ErrorCheckboxGroupExample,
  ErrorControlGroupExample,
  ErrorRadioGroupExample,
  HorizontalRadioGroupExample,
  IndeterminateCheckboxExample,
  MultiColumnControlGroupExample,
  RadioControlGroupExample,
  RadioGroupExample,
  RadioWithDescriptionExample,
  ReadOnlyCheckboxExample,
  ReadOnlySwitchExample,
  RequiredCheckboxGroupExample,
  RequiredControlGroupExample,
  RequiredRadioGroupExample,
  SettingsListSwitchExample,
  SwitchControlGroupExample,
  SwitchGroupExample,
  SwitchWithDescriptionExample,
} from './ControlExamples';
import {
  BreadcrumbBasicExample,
  BreadcrumbCurrentPageExample,
  BreadcrumbOverflowExample,
  BasicSideNavigationExample,
  DividerHorizontalExample,
  DividerInsetExample,
  DividerVerticalExample,
  CollapsedSideNavigationExample,
  PaginationBasicExample,
  PaginationCompactExample,
  PaginationWithInputExample,
  SideNavigationWithSubnavExample,
  BasicTabExample,
  BasicIndicatorExample,
  BasicProgressStepperExample,
  DisabledIndicatorExample,
  DisabledTabExample,
  IndicatorInCarouselExample,
  IndicatorSizeExample,
  InteractiveIndicatorExample,
  CompletedProgressStepperExample,
  ErrorProgressStepperExample,
  MultiStepProgressStepperExample,
  TabWithCountExample,
  TabWithHorizontalPaddingExample,
  TabWithSectionTitleExample,
} from './NavigationComponentExamples';
import {
  AnnouncementBannerExample,
  BannerWithLinkExample,
  BasicBannerExample,
  BasicSectionMessageExample,
  BasicToastExample,
  DismissibleBannerExample,
  ErrorBannerExample,
  ErrorSectionMessageExample,
  ErrorToastExample,
  SectionMessageWithDescriptionExample,
  SectionMessageWithDismissExample,
  SectionMessageWithLinkExample,
  SuccessSectionMessageExample,
  SuccessToastExample,
  ToastWithActionExample,
  ToastWithDescriptionExample,
  ToastWithProgressExample,
  WarningBannerExample,
} from './FeedbackComponentExamples';
import {
  BasicTextAreaExample,
  BasicTextInputExample,
  DisabledTextAreaExample,
  DisabledTextInputExample,
  ErrorTextAreaExample,
  ErrorTextInputExample,
  ReadOnlyTextAreaExample,
  RequiredTextInputExample,
  ResizableTextAreaExample,
  TextAreaActionExample,
  TextAreaCopyExample,
  TextAreaCounterExample,
  TextAreaWithHelperExample,
  TextInputLeadingExample,
  TextInputTrailingExample,
  TextInputWithHelperExample,
} from './InputComponentExamples';
import {
  BasicSelectExample,
  MultiSelectExample,
  MultiSelectStatesExample,
  SelectWithCounterBadgeExample,
  SelectWithErrorExample,
  SelectWithLabelHelperExample,
  SingleSelectStatesExample,
  TextSelectExample,
} from './SelectionComponentExamples';
import {
  BadgeBasicExample,
  BadgeColorExample,
  BadgeCounterBasicExample,
  BadgeCounterGreyExample,
  BadgeCounterSizeExample,
  BadgeStatusDotExample,
  BadgeStatusNewExample,
  BadgeStatusNumberExample,
  BadgeWithIconExample,
  ChipBasicExample,
  ChipSizeExample,
  ChipStateExample,
  EmptyStateBasicExample,
  EmptyStateSearchExample,
} from './StatusIndicatorExamples';
import {
  BarSkeletonExample,
  BasicProgressBarExample,
  BasicSkeletonExample,
  BasicSpinnerExample,
  CircleSkeletonExample,
  ErrorProgressBarExample,
  InverseSpinnerExample,
  LargeSpinnerExample,
  ProgressBarWithHelperExample,
  ProgressBarWithPercentageExample,
  ProgressBarWithTopLabelExample,
  RectangleSkeletonExample,
  SmallSpinnerExample,
  SpinnerInContainerExample,
  SpinnerWithLabelExample,
  SpinnerWithLabelRightExample,
  SuccessProgressBarExample,
} from './LoadingComponentExamples';
import {
  BasicStructuredListExample,
  HorizontalStructuredListExample,
  StructuredListWithActionExample,
  StructuredListWithCheckboxExample,
  StructuredListWithOverflowExample,
  StructuredListWithSelectionExample,
  StructuredListWithStatusExample,
  VerticalStructuredListExample,
} from './StructuredListComponentExamples';
import {
  BasicColorPickerExample,
  BasicDateSinglePickerExample,
  BasicDateRangePickerExample,
  BasicTimePickerExample,
  ColorPickerWithInputExample,
  ColorPickerWithLabelExample,
  DateRangePickerFooterExample,
  DateRangePickerQuickExample,
  DateRangePickerTimeExample,
  DateSinglePickerFooterExample,
  DateSinglePickerInFormExample,
  DateSinglePickerSelectionPanelExample,
  DisabledColorPickerExample,
  DisabledDateSinglePickerExample,
  MultiRowColorPickerExample,
  TimePicker24HourExample,
  TimePickerSecondsExample,
  TimePickerWithDatePickerExample,
  TimePickerWithoutFooterExample,
} from './PickerComponentExamples';
import {
  BasicMenuExample,
  CascadingMenuExample,
  IconTriggerMenuExample,
  SelectTriggerMenuExample,
} from './MenuExamples';
import {
  BasicUploadExample,
  DragUploadExample,
  ErrorUploadExample,
  UploadingExample,
} from './UploadExamples';
import * as ButtonStories from '../stories/Button.stories';
import * as AccordionStories from '../stories/Accordion.stories';
import * as BannerStories from '../stories/Banner.stories';
import * as BreadcrumbStories from '../stories/Breadcrumb.stories';
import * as ChipStories from '../stories/Chip.stories';
import * as DropdownItemStories from '../stories/DropdownItem.stories';
import * as IconStories from '../stories/Icon.stories';
import * as SectionMessageStories from '../stories/SectionMessage.stories';
import * as SelectStories from '../stories/Select.stories';
import * as SideNavigationStories from '../stories/SideNavigation.stories';
import * as StructuredListStories from '../stories/StructuredList.stories';
import * as TabStories from '../stories/Tab.stories';
import * as TextHelperStories from '../stories/TextHelper.stories';
import * as TextLabelStories from '../stories/TextLabel.stories';

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type StoryEntry = {
  component: ComponentType<any>;
  args: Record<string, unknown>;
  previewClassName?: string;
};

function makeEntry(story: unknown): StoryEntry {
  const s = story as { args?: ButtonProps; render?: (args: ButtonProps) => ReactElement };

  if (s.render) {
    return {
      component: () => s.render?.((s.args ?? {}) as ButtonProps) ?? <></>,
      args: {},
    };
  }

  return {
    component: Button,
    args: (s.args ?? {}) as Record<string, unknown>,
  };
}

function makeRenderedEntry(story: unknown, previewClassName?: string): StoryEntry {
  const s = story as { args?: Record<string, unknown>; render?: (args: Record<string, unknown>) => ReactElement };
  return {
    component: () => s.render?.(s.args ?? {}) ?? <></>,
    args: {},
    previewClassName,
  };
}

function makeStoryEntry(story: unknown, storyModule: unknown, previewClassName?: string): StoryEntry {
  const s = story as { args?: Record<string, unknown>; render?: (args: Record<string, unknown>) => ReactElement };
  const meta = (storyModule as { default?: { args?: Record<string, unknown>; component?: ComponentType<any> } }).default;
  const component = meta?.component;
  const args = { ...(meta?.args ?? {}), ...(s.args ?? {}) };

  if (s.render) {
    return {
      component: () => s.render?.(args) ?? <></>,
      args: {},
      previewClassName,
    };
  }

  return {
    component: component ?? (() => <></>),
    args,
    previewClassName,
  };
}

export const storyRegistry: Record<string, StoryEntry> = {
  'components-button-button--primary-solid':   makeEntry(ButtonStories.PrimarySolid),
  'components-button-button--outlined-button': makeEntry(ButtonStories.OutlinedButton),
  'components-button-button--tertiary':        makeEntry(ButtonStories.Tertiary),
  'components-button-button--primary-ghost':   makeEntry(ButtonStories.PrimaryGhost),
  'components-button-button--ghost-secondary': makeEntry(ButtonStories.GhostSecondary),
  'components-button-button--ghost-inverse':   { ...makeEntry(ButtonStories.GhostInverse), previewClassName: '!bg-primary' },
  'components-button-button--link':            makeEntry(ButtonStories.Link),
  'components-button-button--link-inverse':    { ...makeEntry(ButtonStories.LinkInverse), previewClassName: '!bg-primary' },
  'components-button-button--danger':          makeEntry(ButtonStories.Danger),
  'components-button-button--loading':         makeEntry(ButtonStories.Loading),
  'components-button-button--sizes':           makeRenderedEntry(ButtonStories.Sizes),
  'components-button-button--state':           makeRenderedEntry(ButtonStories.State),
  'components-button-button--left-icon':       makeEntry(ButtonStories.LeftIcon),
  'components-button-button--right-icon':      makeEntry(ButtonStories.RightIcon),
  'components-icon-button--basic':      { component: BasicIconButtonExample, args: {} },
  'components-icon-button--variants':   { component: IconButtonVariantsExample, args: {} },
  'components-icon-button--sizes':      { component: IconButtonSizesExample, args: {} },
  'components-icon-button--states':     { component: IconButtonStatesExample, args: {} },
  'components-icon-button--group':      { component: IconButtonGroupExample, args: {} },
  'components-split-button--basic':     { component: BasicSplitButtonExample, args: {} },
  'components-split-button--with-icon': { component: SplitButtonWithIconExample, args: {} },
  'components-split-button--sizes':     { component: SplitButtonSizesExample, args: {} },
  'components-split-button--states':    { component: SplitButtonStatesExample, args: {} },
  'components-split-button--menu':      { component: SplitButtonMenuExample, args: {} },
  'components-segmented-control--basic': { component: BasicSegmentedControlExample, args: {} },
  'components-toggle-button--basic':      { component: BasicToggleButtonExample, args: {} },
  'components-toggle-button--with-badge': { component: ToggleButtonWithBadgeExample, args: {} },
  'components-toggle-button--group':      { component: ToggleButtonGroupExample, args: {} },
  'components-toggle-button--sizes':      { component: ToggleButtonSizesExample, args: {} },
  'components-toggle-button--states':     { component: ToggleButtonStatesExample, args: {} },
  'components-accordion--basic':        makeStoryEntry(AccordionStories.Basic, AccordionStories),
  'components-accordion--expanded':     { component: AccordionExpandedExample, args: {} },
  'components-accordion--selectable':   { component: AccordionSelectableExample, args: {} },
  'components-accordion--with-divider': { component: AccordionWithDividerExample, args: {} },
  'components-accordion--sizes':        { component: AccordionSizesExample, args: {} },
  'components-accordion--with-content':   makeStoryEntry(AccordionStories.WithContent, AccordionStories),
  'components-accordion--size-md':        makeStoryEntry(AccordionStories.SizeMd, AccordionStories),
  'components-accordion--size-lg':        makeStoryEntry(AccordionStories.SizeLg, AccordionStories),
  'components-accordion--allow-multiple': makeStoryEntry(AccordionStories.AllowMultiple, AccordionStories),
  'components-accordion--no-divider':     makeStoryEntry(AccordionStories.NoDivider, AccordionStories),
  'components-accordion--with-disabled':  makeStoryEntry(AccordionStories.WithDisabled, AccordionStories),
  'components-accordion--long-labels':    makeStoryEntry(AccordionStories.LongLabels, AccordionStories),
  'components-card--basic':             { component: BasicCardExample, args: {} },
  'components-card--without-image':     { component: CardWithoutImageExample, args: {} },
  'components-card--horizontal':        { component: CardHorizontalExample, args: {} },
  'components-card--states':            { component: CardStatesExample, args: {} },
  'components-dropdown-dropdown--default':        { component: DefaultDropdownExample, args: {} },
  'components-dropdown-dropdown--checkbox':       { component: CheckboxDropdownExample, args: {} },
  'components-dropdown-dropdown--avatar':         { component: AvatarDropdownExample, args: {} },
  'components-dropdown-dropdown--flag':           { component: FlagDropdownExample, args: {} },
  'components-dropdown-dropdown--grouped':        { component: GroupedDropdownExample, args: {} },
  'components-dropdown-dropdown--state':          { component: DropdownStateExample, args: {} },
  'components-tree-menu--basic':                  { component: BasicTreeMenuExample, args: {} },
  'components-tree-menu--with-count':             { component: TreeMenuWithCountExample, args: {} },
  'components-tree-menu--with-leading-icon':      { component: TreeMenuWithLeadingIconExample, args: {} },
  'components-tree-menu--selectable':             { component: SelectableTreeMenuExample, args: {} },
  'components-tree-menu--expanded-collapsed':     { component: ExpandedCollapsedTreeMenuExample, args: {} },
  'components-tree-menu--disabled-item':          { component: DisabledTreeMenuExample, args: {} },
  'components-table--basic':                      { component: BasicTableExample, args: {} },
  'components-table--selectable':                 { component: SelectableTableExample, args: {} },
  'components-table--with-status':                { component: TableWithStatusExample, args: {} },
  'components-table--with-pagination':            { component: TableWithPaginationExample, args: {} },
  'components-table--fixed-action-column':        { component: TableWithFixedActionColumnExample, args: {} },
  'components-table-tree--basic':                 { component: BasicTableTreeExample, args: {} },
  'components-table-tree--with-badge':            { component: TableTreeWithBadgeExample, args: {} },
  'components-table-tree--selected-row':          { component: TableTreeWithSelectedRowExample, args: {} },
  'components-table-tree--expanded':              { component: ExpandedTableTreeExample, args: {} },
  'components-table-tree--multi-level':           { component: MultiLevelHierarchyExample, args: {} },
  'components-table-toolbar--metadata':           { component: MetadataToolbarExample, args: {} },
  'components-table-toolbar--with-search':        { component: ToolbarWithSearchExample, args: {} },
  'components-table-toolbar--with-actions':       { component: ToolbarWithActionsExample, args: {} },
  'components-table-toolbar--column-visibility':  { component: ToolbarWithColumnVisibilityExample, args: {} },
  'components-table-toolbar--with-table':         { component: ToolbarWithTableExample, args: {} },
  'components-controls-checkbox--basic':                   { component: BasicCheckboxExample, args: {} },
  'components-controls-checkbox--with-description':        { component: CheckboxWithDescriptionExample, args: {} },
  'components-controls-checkbox--group':                   { component: CheckboxGroupExample, args: {} },
  'components-controls-checkbox--required-group':          { component: RequiredCheckboxGroupExample, args: {} },
  'components-controls-checkbox--error-group':             { component: ErrorCheckboxGroupExample, args: {} },
  'components-controls-checkbox--disabled':                { component: DisabledCheckboxExample, args: {} },
  'components-controls-checkbox--read-only':               { component: ReadOnlyCheckboxExample, args: {} },
  'components-controls-checkbox--indeterminate':           { component: IndeterminateCheckboxExample, args: {} },
  'components-controls-radio--basic':                      { component: BasicRadioExample, args: {} },
  'components-controls-radio--with-description':           { component: RadioWithDescriptionExample, args: {} },
  'components-controls-radio--group':                      { component: RadioGroupExample, args: {} },
  'components-controls-radio--required-group':             { component: RequiredRadioGroupExample, args: {} },
  'components-controls-radio--error-group':                { component: ErrorRadioGroupExample, args: {} },
  'components-controls-radio--disabled':                   { component: DisabledRadioExample, args: {} },
  'components-controls-radio--horizontal-group':           { component: HorizontalRadioGroupExample, args: {} },
  'components-control-group--radio':              { component: RadioControlGroupExample, args: {} },
  'components-control-group--checkbox':           { component: CheckboxControlGroupExample, args: {} },
  'components-control-group--switch':             { component: SwitchControlGroupExample, args: {} },
  'components-control-group--with-description':   { component: ControlGroupWithDescriptionExample, args: {} },
  'components-control-group--required':           { component: RequiredControlGroupExample, args: {} },
  'components-control-group--error':              { component: ErrorControlGroupExample, args: {} },
  'components-control-group--multi-column':       { component: MultiColumnControlGroupExample, args: {} },
  'components-controls-switch--basic':                     { component: BasicSwitchExample, args: {} },
  'components-controls-switch--with-description':          { component: SwitchWithDescriptionExample, args: {} },
  'components-controls-switch--group':                     { component: SwitchGroupExample, args: {} },
  'components-controls-switch--disabled':                  { component: DisabledSwitchExample, args: {} },
  'components-controls-switch--read-only':                 { component: ReadOnlySwitchExample, args: {} },
  'components-controls-switch--settings-list':             { component: SettingsListSwitchExample, args: {} },
  'components-navigation-breadcrumb--basic':                 { component: BreadcrumbBasicExample, args: {} },
  'components-navigation-breadcrumb--overflow':              { component: BreadcrumbOverflowExample, args: {} },
  'components-navigation-breadcrumb--current-page':          { component: BreadcrumbCurrentPageExample, args: {} },
  'components-navigation-breadcrumb--default':               makeStoryEntry(BreadcrumbStories.Default, BreadcrumbStories),
  'components-navigation-breadcrumb--deep':                  makeStoryEntry(BreadcrumbStories.Deep, BreadcrumbStories),
  'components-navigation-breadcrumb--collapsed':             makeStoryEntry(BreadcrumbStories.Collapsed, BreadcrumbStories),
  'components-navigation-breadcrumb--minimal':               makeStoryEntry(BreadcrumbStories.Minimal, BreadcrumbStories),
  'components-navigation-breadcrumb--long-labels':           makeStoryEntry(BreadcrumbStories.LongLabels, BreadcrumbStories),
  'components-divider--horizontal':               { component: DividerHorizontalExample, args: {} },
  'components-divider--vertical':                 { component: DividerVerticalExample, args: {} },
  'components-divider--inset':                    { component: DividerInsetExample, args: {} },
  'components-pagination--basic':                 { component: PaginationBasicExample, args: {} },
  'components-pagination--with-input':            { component: PaginationWithInputExample, args: {} },
  'components-pagination--compact':               { component: PaginationCompactExample, args: {} },
  'components-indicator--basic':                  { component: BasicIndicatorExample, args: {} },
  'components-indicator--size':                   { component: IndicatorSizeExample, args: {} },
  'components-indicator--carousel':               { component: IndicatorInCarouselExample, args: {} },
  'components-indicator--interactive':            { component: InteractiveIndicatorExample, args: {} },
  'components-indicator--disabled':               { component: DisabledIndicatorExample, args: {} },
  'components-side-navigation--basic':            { component: BasicSideNavigationExample, args: {} },
  'components-side-navigation--collapsed':        { component: CollapsedSideNavigationExample, args: {} },
  'components-side-navigation--subnav':           { component: SideNavigationWithSubnavExample, args: {} },
  'components-navigation-sidenavigation--expanded':          makeStoryEntry(SideNavigationStories.Expanded, SideNavigationStories),
  'components-navigation-sidenavigation--expanded-flat':     makeStoryEntry(SideNavigationStories.ExpandedFlat, SideNavigationStories),
  'components-navigation-sidenavigation--collapsed':         makeStoryEntry(SideNavigationStories.Collapsed, SideNavigationStories),
  'components-navigation-sidenavigation--with-disabled':     makeStoryEntry(SideNavigationStories.WithDisabled, SideNavigationStories),
  'components-navigation-sidenavigation--multiple-groups':   makeStoryEntry(SideNavigationStories.MultipleGroups, SideNavigationStories),
  'components-progress-stepper--basic':           { component: BasicProgressStepperExample, args: {} },
  'components-progress-stepper--completed':       { component: CompletedProgressStepperExample, args: {} },
  'components-progress-stepper--error':           { component: ErrorProgressStepperExample, args: {} },
  'components-progress-stepper--multi-step':      { component: MultiStepProgressStepperExample, args: {} },
  'components-tab--basic':                        { component: BasicTabExample, args: {} },
  'components-tab--with-count':                   { component: TabWithCountExample, args: {} },
  'components-tab--horizontal-padding':           { component: TabWithHorizontalPaddingExample, args: {} },
  'components-tab--with-section-title':           { component: TabWithSectionTitleExample, args: {} },
  'components-tab--disabled':                     { component: DisabledTabExample, args: {} },
  'components-navigation-tabs--size-md':                     makeStoryEntry(TabStories.SizeMd, TabStories),
  'components-navigation-tabs--size-sm':                     makeStoryEntry(TabStories.SizeSm, TabStories),
  'components-navigation-tabs--with-disabled':               makeStoryEntry(TabStories.WithDisabled, TabStories),
  'components-navigation-tabs--disabled-selected':           makeStoryEntry(TabStories.DisabledSelected, TabStories),
  'components-navigation-tabs--with-badge':                  makeStoryEntry(TabStories.WithBadge, TabStories),
  'components-navigation-tabs--with-dot':                    makeStoryEntry(TabStories.WithDot, TabStories),
  'components-navigation-tabs--mixed':                       makeStoryEntry(TabStories.Mixed, TabStories),
  'components-navigation-tabs--sm-with-badge':               makeStoryEntry(TabStories.SmWithBadge, TabStories),
  'components-toast-message--basic':              { component: BasicToastExample, args: {} },
  'components-toast-message--with-description':   { component: ToastWithDescriptionExample, args: {} },
  'components-toast-message--with-action':        { component: ToastWithActionExample, args: {} },
  'components-toast-message--with-progress':      { component: ToastWithProgressExample, args: {} },
  'components-toast-message--success':            { component: SuccessToastExample, args: {} },
  'components-toast-message--error':              { component: ErrorToastExample, args: {} },
  'components-section-message--basic':            { component: BasicSectionMessageExample, args: {} },
  'components-section-message--with-description': { component: SectionMessageWithDescriptionExample, args: {} },
  'components-section-message--with-link':        { component: SectionMessageWithLinkExample, args: {} },
  'components-section-message--with-dismiss':     { component: SectionMessageWithDismissExample, args: {} },
  'components-section-message--error':            { component: ErrorSectionMessageExample, args: {} },
  'components-section-message--success':          { component: SuccessSectionMessageExample, args: {} },
  'components-feedback-sectionmessage--neutral':           makeStoryEntry(SectionMessageStories.Neutral, SectionMessageStories),
  'components-feedback-sectionmessage--info':              makeStoryEntry(SectionMessageStories.Info, SectionMessageStories),
  'components-feedback-sectionmessage--success':           makeStoryEntry(SectionMessageStories.Success, SectionMessageStories),
  'components-feedback-sectionmessage--warning':           makeStoryEntry(SectionMessageStories.Warning, SectionMessageStories),
  'components-feedback-sectionmessage--error':             makeStoryEntry(SectionMessageStories.Error, SectionMessageStories),
  'components-feedback-sectionmessage--brand-light':       makeStoryEntry(SectionMessageStories.BrandLight, SectionMessageStories),
  'components-feedback-sectionmessage--without-actions':   makeStoryEntry(SectionMessageStories.WithoutActions, SectionMessageStories),
  'components-feedback-sectionmessage--all-statuses':      makeStoryEntry(SectionMessageStories.AllStatuses, SectionMessageStories),
  'components-feedback-banner--basic':                     { component: BasicBannerExample, args: {} },
  'components-feedback-banner--error':                     makeStoryEntry(BannerStories.Error, BannerStories),
  'components-feedback-banner--warning':                   makeStoryEntry(BannerStories.Warning, BannerStories),
  'components-feedback-banner--announcement':              makeStoryEntry(BannerStories.Announcement, BannerStories),
  'components-feedback-banner--with-link':                 { component: BannerWithLinkExample, args: {} },
  'components-feedback-banner--dismissible':               { component: DismissibleBannerExample, args: {} },
  'components-feedback-banner--brand':                     makeStoryEntry(BannerStories.Brand, BannerStories),
  'components-feedback-banner--without-action':            makeStoryEntry(BannerStories.WithoutAction, BannerStories),
  'components-feedback-banner--all-colors':                makeStoryEntry(BannerStories.AllColors, BannerStories),
  'components-text-input--basic':                 { component: BasicTextInputExample, args: {} },
  'components-text-input--with-helper':           { component: TextInputWithHelperExample, args: {} },
  'components-text-input--required':              { component: RequiredTextInputExample, args: {} },
  'components-text-input--leading':               { component: TextInputLeadingExample, args: {} },
  'components-text-input--trailing-button':       { component: TextInputTrailingExample, args: {} },
  'components-text-input--error':                 { component: ErrorTextInputExample, args: {} },
  'components-text-input--disabled':              { component: DisabledTextInputExample, args: {} },
  'components-text-area--basic':                  { component: BasicTextAreaExample, args: {} },
  'components-text-area--with-helper':            { component: TextAreaWithHelperExample, args: {} },
  'components-text-area--with-counter':           { component: TextAreaCounterExample, args: {} },
  'components-text-area--with-action':            { component: TextAreaActionExample, args: {} },
  'components-text-area--with-copy':              { component: TextAreaCopyExample, args: {} },
  'components-text-area--resizable':              { component: ResizableTextAreaExample, args: {} },
  'components-text-area--error':                  { component: ErrorTextAreaExample, args: {} },
  'components-text-area--disabled':               { component: DisabledTextAreaExample, args: {} },
  'components-text-area--read-only':              { component: ReadOnlyTextAreaExample, args: {} },
  'components-loading-progressbar--small':               { component: BasicProgressBarExample, args: {} },
  'components-loading-progressbar--medium':              { component: ProgressBarWithTopLabelExample, args: {} },
  'components-loading-progressbar--states':              { component: ProgressBarWithHelperExample, args: {} },
  'components-loading-progressbar--no-label':            { component: ProgressBarWithPercentageExample, args: {} },
  'components-loading-progressbar--no-value':            { component: SuccessProgressBarExample, args: {} },
  'components-loading-progressbar--table-sizes':         { component: ErrorProgressBarExample, args: {} },
  'components-loading-progressbar--table-with-number':   { component: ErrorProgressBarExample, args: {} },
  'components-loading-progressbar--table-values':        { component: ErrorProgressBarExample, args: {} },
  'components-loading-spinner--below-sm':                 { component: BasicSpinnerExample, args: {} },
  'components-loading-spinner--below-md':                 { component: SpinnerWithLabelExample, args: {} },
  'components-loading-spinner--below-lg':                 { component: SpinnerWithLabelRightExample, args: {} },
  'components-loading-spinner--right-sm':                 { component: InverseSpinnerExample, args: {} },
  'components-loading-spinner--right-md':                 { component: SmallSpinnerExample, args: {} },
  'components-loading-spinner--right-lg':                 { component: LargeSpinnerExample, args: {} },
  'components-loading-spinner--sizes':                    { component: SpinnerInContainerExample, args: {} },
  'components-loading-spinner--inverse':                  { component: InverseSpinnerExample, args: {} },
  'components-loading-spinner--no-label':                 { component: SpinnerInContainerExample, args: {} },
  'components-loading-skeleton--items':                   { component: BasicSkeletonExample, args: {} },
  'components-loading-skeleton--card':                    { component: CircleSkeletonExample, args: {} },
  'components-loading-skeleton--text':                    { component: BarSkeletonExample, args: {} },
  'components-loading-skeleton--list':                    { component: RectangleSkeletonExample, args: {} },
  'components-select-select--basic':                     { component: BasicSelectExample, args: {} },
  'components-select-select--label-helper':              { component: SelectWithLabelHelperExample, args: {} },
  'components-select-select--text':                      { component: TextSelectExample, args: {} },
  'components-select-select--single-states':             { component: SingleSelectStatesExample, args: {} },
  'components-select-select--multi':                     { component: MultiSelectExample, args: {} },
  'components-select-select--multi-states':              { component: MultiSelectStatesExample, args: {} },
  'components-select-select--error':                     makeStoryEntry(SelectStories.Error, SelectStories),
  'components-select-select--counter':                   { component: SelectWithCounterBadgeExample, args: {} },
  'components-select-select--placeholder':               makeStoryEntry(SelectStories.Placeholder, SelectStories),
  'components-select-select--done':                      makeStoryEntry(SelectStories.Done, SelectStories),
  'components-select-select--disabled':                  makeStoryEntry(SelectStories.Disabled, SelectStories),
  'components-select-select--readonly':                  makeStoryEntry(SelectStories.Readonly, SelectStories),
  'components-select-select--with-helper-text':          makeStoryEntry(SelectStories.WithHelperText, SelectStories),
  'components-select-select--required':                  makeStoryEntry(SelectStories.Required, SelectStories),
  'components-select-select--all-states':                makeStoryEntry(SelectStories.AllStates, SelectStories),
  'components-select-select--multi-placeholder':         makeStoryEntry(SelectStories.MultiPlaceholder, SelectStories),
  'components-select-select--multi-done':                makeStoryEntry(SelectStories.MultiDone, SelectStories),
  'components-select-select--multi-error':               makeStoryEntry(SelectStories.MultiError, SelectStories),
  'components-select-select--multi-disabled':            makeStoryEntry(SelectStories.MultiDisabled, SelectStories),
  'components-select-select--all-multi-states':          makeStoryEntry(SelectStories.AllMultiStates, SelectStories),
  'components-select-select--with-long-options':         makeStoryEntry(SelectStories.WithLongOptions, SelectStories),
  'components-select-select--sm-vs-md':                  makeStoryEntry(SelectStories.SmVsMd, SelectStories),
  'components-status-indicator-badge--basic':                      { component: BadgeBasicExample, args: {} },
  'components-status-indicator-badge--with-icon':                  { component: BadgeWithIconExample, args: {} },
  'components-status-indicator-badge--color':                      { component: BadgeColorExample, args: {} },
  'components-badge-counter--basic':              { component: BadgeCounterBasicExample, args: {} },
  'components-badge-counter--size':               { component: BadgeCounterSizeExample, args: {} },
  'components-badge-counter--grey':               { component: BadgeCounterGreyExample, args: {} },
  'components-badge-status--number':              { component: BadgeStatusNumberExample, args: {} },
  'components-badge-status--dot':                 { component: BadgeStatusDotExample, args: {} },
  'components-badge-status--new':                 { component: BadgeStatusNewExample, args: {} },
  'components-status-indicator-chip--basic':                       { component: ChipBasicExample, args: {} },
  'components-status-indicator-chip--size':                        { component: ChipSizeExample, args: {} },
  'components-status-indicator-chip--state':                       { component: ChipStateExample, args: {} },
  'components-status-indicator-chip--sm-selected':                 makeStoryEntry(ChipStories.SmSelected, ChipStories),
  'components-status-indicator-chip--sm-default':                  makeStoryEntry(ChipStories.SmDefault, ChipStories),
  'components-status-indicator-chip--md-selected':                 makeStoryEntry(ChipStories.MdSelected, ChipStories),
  'components-status-indicator-chip--md-default':                  makeStoryEntry(ChipStories.MdDefault, ChipStories),
  'components-status-indicator-chip--all-variants':                makeStoryEntry(ChipStories.AllVariants, ChipStories),
  'components-status-indicator-chip--icon-variants':               makeStoryEntry(ChipStories.IconVariants, ChipStories),
  'foundation-icon--icon-sizes':                  makeStoryEntry(IconStories.IconSizes, IconStories),
  'foundation-icon--with-custom-icon':            makeStoryEntry(IconStories.WithCustomIcon, IconStories),
  'components-dropdown-dropdownitem--default':             makeStoryEntry(DropdownItemStories.Default, DropdownItemStories),
  'components-dropdown-dropdownitem--selected':            makeStoryEntry(DropdownItemStories.Selected, DropdownItemStories),
  'components-dropdown-dropdownitem--focused':             makeStoryEntry(DropdownItemStories.Focused, DropdownItemStories),
  'components-dropdown-dropdownitem--disabled':            makeStoryEntry(DropdownItemStories.Disabled, DropdownItemStories),
  'components-dropdown-dropdownitem--radio':               makeStoryEntry(DropdownItemStories.Radio, DropdownItemStories),
  'components-dropdown-dropdownitem--checkbox':            makeStoryEntry(DropdownItemStories.Checkbox, DropdownItemStories),
  'components-dropdown-dropdownitem--all-variants':        makeStoryEntry(DropdownItemStories.AllVariants, DropdownItemStories),
  'components-input-texthelper--default':               makeStoryEntry(TextHelperStories.Default, TextHelperStories),
  'components-input-texthelper--error':                 makeStoryEntry(TextHelperStories.Error, TextHelperStories),
  'components-input-texthelper--all-variants':          makeStoryEntry(TextHelperStories.AllVariants, TextHelperStories),
  'components-input-textlabel--md':                     makeStoryEntry(TextLabelStories.Md, TextLabelStories),
  'components-input-textlabel--md-required':            makeStoryEntry(TextLabelStories.MdRequired, TextLabelStories),
  'components-input-textlabel--sm':                     makeStoryEntry(TextLabelStories.Sm, TextLabelStories),
  'components-input-textlabel--sm-required':            makeStoryEntry(TextLabelStories.SmRequired, TextLabelStories),
  'components-input-textlabel--all-variants':           makeStoryEntry(TextLabelStories.AllVariants, TextLabelStories),
  'components-empty-state--basic':                { component: EmptyStateBasicExample, args: {} },
  'components-empty-state--search':               { component: EmptyStateSearchExample, args: {} },
  'components-structured-list--basic':            { component: BasicStructuredListExample, args: {} },
  'components-structured-list--checkbox':         { component: StructuredListWithCheckboxExample, args: {} },
  'components-structured-list--status':           { component: StructuredListWithStatusExample, args: {} },
  'components-structured-list--action':           { component: StructuredListWithActionExample, args: {} },
  'components-structured-list--horizontal':       { component: HorizontalStructuredListExample, args: {} },
  'components-structured-list--vertical':         { component: VerticalStructuredListExample, args: {} },
  'components-structured-list--overflow':         { component: StructuredListWithOverflowExample, args: {} },
  'components-structured-list--selection':        { component: StructuredListWithSelectionExample, args: {} },
  'components-structured-list-structuredlist--vertical':          makeStoryEntry(StructuredListStories.Vertical, StructuredListStories),
  'components-structured-list-structuredlist--vertical-no-divider': makeStoryEntry(StructuredListStories.VerticalNoDivider, StructuredListStories),
  'components-structured-list-structuredlist--horizontal':        makeStoryEntry(StructuredListStories.Horizontal, StructuredListStories),
  'components-structured-list-structuredlist--horizontal-no-divider': makeStoryEntry(StructuredListStories.HorizontalNoDivider, StructuredListStories),
  'components-color-picker--basic':               { component: BasicColorPickerExample, args: {} },
  'components-color-picker--with-label':          { component: ColorPickerWithLabelExample, args: {} },
  'components-color-picker--with-input':          { component: ColorPickerWithInputExample, args: {} },
  'components-color-picker--multi-row':           { component: MultiRowColorPickerExample, args: {} },
  'components-color-picker--disabled':            { component: DisabledColorPickerExample, args: {} },
  'components-date-range-picker--basic':          { component: BasicDateRangePickerExample, args: {} },
  'components-date-range-picker--quick-select':   { component: DateRangePickerQuickExample, args: {} },
  'components-date-range-picker--time-input':     { component: DateRangePickerTimeExample, args: {} },
  'components-date-range-picker--footer-actions': { component: DateRangePickerFooterExample, args: {} },
  'components-date-single-picker--basic':          { component: BasicDateSinglePickerExample, args: {} },
  'components-date-single-picker--selection-panel': { component: DateSinglePickerSelectionPanelExample, args: {} },
  'components-date-single-picker--footer':         { component: DateSinglePickerFooterExample, args: {} },
  'components-date-single-picker--disabled-date':  { component: DisabledDateSinglePickerExample, args: {} },
  'components-date-single-picker--in-form':        { component: DateSinglePickerInFormExample, args: {} },
  'components-time-picker--basic':                 { component: BasicTimePickerExample, args: {} },
  'components-time-picker--24-hour':               { component: TimePicker24HourExample, args: {} },
  'components-time-picker--seconds':               { component: TimePickerSecondsExample, args: {} },
  'components-time-picker--without-footer':        { component: TimePickerWithoutFooterExample, args: {} },
  'components-time-picker--with-date-picker':      { component: TimePickerWithDatePickerExample, args: {} },
  'components-menu--basic':                        { component: BasicMenuExample, args: {} },
  'components-menu--cascading':                    { component: CascadingMenuExample, args: {} },
  'components-menu--icon-trigger':                 { component: IconTriggerMenuExample, args: {} },
  'components-menu--select-trigger':               { component: SelectTriggerMenuExample, args: {} },
  'components-upload--basic':                      { component: BasicUploadExample, args: {} },
  'components-upload--drag':                       { component: DragUploadExample, args: {} },
  'components-upload--uploading':                  { component: UploadingExample, args: {} },
  'components-upload--error':                      { component: ErrorUploadExample, args: {} },
};
