// Maps Storybook story IDs → source code strings.
// Source is extracted from the same `parameters.docs.source.code` that Storybook Docs renders,
// so it stays in sync automatically when story args change in the stories files.

import * as ButtonStories from '../stories/Button.stories';
import * as ProgressBarStories from '../stories/ProgressBar.stories';
import * as SkeletonStories from '../stories/Skeleton.stories';
import * as SpinnerStories from '../stories/Spinner.stories';
import * as AccordionStories from '../stories/Accordion.stories';
import * as BannerStories from '../stories/Banner.stories';
import * as BreadcrumbStories from '../stories/Breadcrumb.stories';
import * as ChipStories from '../stories/Chip.stories';
import * as DropdownItemStories from '../stories/DropdownItem.stories';
import * as IconStories from '../stories/Icon.stories';
import * as SectionMessageStories from '../stories/SectionMessage.stories';
import * as SelectStories from '../stories/Select.stories';
import * as SideNavigationStories from '../stories/SideNavigation.stories';
import * as StructuredListStories from '../stories/StructuredList.stories';
import * as TabStories from '../stories/Tab.stories';
import * as TextHelperStories from '../stories/TextHelper.stories';
import * as TextLabelStories from '../stories/TextLabel.stories';
import {iconButtonSourceMap} from './IconButtonExamples';
import {splitButtonSourceMap} from './SplitButtonExamples';
import {segmentedControlSourceMap} from './SegmentedControlExamples';
import {toggleButtonSourceMap} from './ToggleButtonExamples';
import {accordionSourceMap} from './AccordionExamples';
import {cardSourceMap} from './CardExamples';
import {dropdownSourceMap} from './DropdownExamples';
import {treeMenuSourceMap} from './TreeMenuExamples';
import {controlSourceMap} from './ControlExamples';
import {dataTableSourceMap} from './DataTableExamples';
import {navigationComponentSourceMap} from './NavigationComponentExamples';
import {feedbackComponentSourceMap} from './FeedbackComponentExamples';
import {inputComponentSourceMap} from './InputComponentExamples';
import {selectionComponentSourceMap} from './SelectionComponentExamples';
import {statusIndicatorSourceMap} from './StatusIndicatorExamples';
import {structuredListComponentSourceMap} from './StructuredListComponentExamples';
import {pickerComponentSourceMap} from './PickerComponentExamples';
import {menuSourceMap} from './MenuExamples';
import {uploadSourceMap} from './UploadExamples';

type AnyObj = Record<string, unknown>;

function extractCode(story: unknown): string {
  try {
    const params = (story as AnyObj)?.parameters as AnyObj;
    const code = ((params?.docs as AnyObj)?.source as AnyObj)?.code;
    return typeof code === 'string' ? code : '';
  } catch {
    return '';
  }
}

export const storySourceMap: Record<string, string> = {
  'components-button-button--primary-solid':   extractCode(ButtonStories.PrimarySolid),
  'components-button-button--outlined-button': extractCode(ButtonStories.OutlinedButton),
  'components-button-button--tertiary':        extractCode(ButtonStories.Tertiary),
  'components-button-button--primary-ghost':   extractCode(ButtonStories.PrimaryGhost),
  'components-button-button--ghost-secondary': extractCode(ButtonStories.GhostSecondary),
  'components-button-button--ghost-inverse':   extractCode(ButtonStories.GhostInverse),
  'components-button-button--link':            extractCode(ButtonStories.Link),
  'components-button-button--link-inverse':    extractCode(ButtonStories.LinkInverse),
  'components-button-button--danger':          extractCode(ButtonStories.Danger),
  'components-button-button--loading':         extractCode(ButtonStories.Loading),
  'components-button-button--sizes':           extractCode(ButtonStories.Sizes),
  'components-button-button--state':           extractCode(ButtonStories.State),
  'components-button-button--left-icon':       extractCode(ButtonStories.LeftIcon),
  'components-button-button--right-icon':      extractCode(ButtonStories.RightIcon),
  'components-icon-button--basic':      iconButtonSourceMap.basic,
  'components-icon-button--variants':   iconButtonSourceMap.variants,
  'components-icon-button--sizes':      iconButtonSourceMap.sizes,
  'components-icon-button--states':     iconButtonSourceMap.states,
  'components-icon-button--group':      iconButtonSourceMap.group,
  'components-split-button--basic':     splitButtonSourceMap.basic,
  'components-split-button--with-icon': splitButtonSourceMap.withIcon,
  'components-split-button--sizes':     splitButtonSourceMap.sizes,
  'components-split-button--states':    splitButtonSourceMap.states,
  'components-split-button--menu':      splitButtonSourceMap.menu,
  'components-segmented-control--basic': segmentedControlSourceMap.basic,
  'components-toggle-button--basic':      toggleButtonSourceMap.basic,
  'components-toggle-button--with-badge': toggleButtonSourceMap.withBadge,
  'components-toggle-button--group':      toggleButtonSourceMap.group,
  'components-toggle-button--sizes':      toggleButtonSourceMap.sizes,
  'components-toggle-button--states':     toggleButtonSourceMap.states,
  'components-accordion--basic':        accordionSourceMap.basic,
  'components-accordion--expanded':     accordionSourceMap.expanded,
  'components-accordion--selectable':   accordionSourceMap.selectable,
  'components-accordion--with-divider': accordionSourceMap.withDivider,
  'components-accordion--sizes':        accordionSourceMap.sizes,
  'components-accordion--with-content':   extractCode(AccordionStories.WithContent),
  'components-accordion--size-md':        extractCode(AccordionStories.SizeMd),
  'components-accordion--size-lg':        extractCode(AccordionStories.SizeLg),
  'components-accordion--allow-multiple': extractCode(AccordionStories.AllowMultiple),
  'components-accordion--no-divider':     extractCode(AccordionStories.NoDivider),
  'components-accordion--with-disabled':  extractCode(AccordionStories.WithDisabled),
  'components-accordion--long-labels':    extractCode(AccordionStories.LongLabels),
  'components-card--basic':             cardSourceMap.basic,
  'components-card--without-image':     cardSourceMap.withoutImage,
  'components-card--horizontal':        cardSourceMap.horizontal,
  'components-card--states':            cardSourceMap.states,
  'components-dropdown-dropdown--default':        dropdownSourceMap.default,
  'components-dropdown-dropdown--checkbox':       dropdownSourceMap.checkbox,
  'components-dropdown-dropdown--avatar':         dropdownSourceMap.avatar,
  'components-dropdown-dropdown--flag':           dropdownSourceMap.flag,
  'components-dropdown-dropdown--grouped':        dropdownSourceMap.grouped,
  'components-dropdown-dropdown--state':          dropdownSourceMap.state,
  'components-tree-menu--basic':                  treeMenuSourceMap.basic,
  'components-tree-menu--with-count':             treeMenuSourceMap.count,
  'components-tree-menu--with-leading-icon':      treeMenuSourceMap.leadingIcon,
  'components-tree-menu--selectable':             treeMenuSourceMap.selectable,
  'components-tree-menu--expanded-collapsed':     treeMenuSourceMap.expandedCollapsed,
  'components-tree-menu--disabled-item':          treeMenuSourceMap.disabled,
  'components-table--basic':                      dataTableSourceMap.basicTable,
  'components-table--selectable':                 dataTableSourceMap.selectableTable,
  'components-table--with-status':                dataTableSourceMap.tableWithStatus,
  'components-table--with-pagination':            dataTableSourceMap.tableWithPagination,
  'components-table--fixed-action-column':        dataTableSourceMap.tableWithFixedAction,
  'components-table-tree--basic':                 dataTableSourceMap.basicTableTree,
  'components-table-tree--with-badge':            dataTableSourceMap.tableTreeWithBadge,
  'components-table-tree--selected-row':          dataTableSourceMap.tableTreeSelected,
  'components-table-tree--expanded':              dataTableSourceMap.expandedTableTree,
  'components-table-tree--multi-level':           dataTableSourceMap.multiLevelHierarchy,
  'components-table-toolbar--metadata':           dataTableSourceMap.metadataToolbar,
  'components-table-toolbar--with-search':        dataTableSourceMap.toolbarWithSearch,
  'components-table-toolbar--with-actions':       dataTableSourceMap.toolbarWithActions,
  'components-table-toolbar--column-visibility':  dataTableSourceMap.toolbarWithColumnVisibility,
  'components-table-toolbar--with-table':         dataTableSourceMap.toolbarWithTable,
  'components-controls-checkbox--basic':                   controlSourceMap.checkboxBasic,
  'components-controls-checkbox--with-description':        controlSourceMap.checkboxDescription,
  'components-controls-checkbox--group':                   controlSourceMap.checkboxGroup,
  'components-controls-checkbox--required-group':          controlSourceMap.checkboxRequired,
  'components-controls-checkbox--error-group':             controlSourceMap.checkboxError,
  'components-controls-checkbox--disabled':                controlSourceMap.checkboxDisabled,
  'components-controls-checkbox--read-only':               controlSourceMap.checkboxReadOnly,
  'components-controls-checkbox--indeterminate':           controlSourceMap.checkboxIndeterminate,
  'components-controls-radio--basic':                      controlSourceMap.radioBasic,
  'components-controls-radio--with-description':           controlSourceMap.radioDescription,
  'components-controls-radio--group':                      controlSourceMap.radioGroup,
  'components-controls-radio--required-group':             controlSourceMap.radioRequired,
  'components-controls-radio--error-group':                controlSourceMap.radioError,
  'components-controls-radio--disabled':                   controlSourceMap.radioDisabled,
  'components-controls-radio--horizontal-group':           controlSourceMap.radioHorizontal,
  'components-control-group--radio':              controlSourceMap.controlRadio,
  'components-control-group--checkbox':           controlSourceMap.controlCheckbox,
  'components-control-group--switch':             controlSourceMap.controlSwitch,
  'components-control-group--with-description':   controlSourceMap.controlDescription,
  'components-control-group--required':           controlSourceMap.controlRequired,
  'components-control-group--error':              controlSourceMap.controlError,
  'components-control-group--multi-column':       controlSourceMap.controlMultiColumn,
  'components-controls-switch--basic':                     controlSourceMap.switchBasic,
  'components-controls-switch--with-description':          controlSourceMap.switchDescription,
  'components-controls-switch--group':                     controlSourceMap.switchGroup,
  'components-controls-switch--disabled':                  controlSourceMap.switchDisabled,
  'components-controls-switch--read-only':                 controlSourceMap.switchReadOnly,
  'components-controls-switch--settings-list':             controlSourceMap.switchSettings,
  'components-navigation-breadcrumb--basic':                 navigationComponentSourceMap.breadcrumbBasic,
  'components-navigation-breadcrumb--overflow':              navigationComponentSourceMap.breadcrumbOverflow,
  'components-navigation-breadcrumb--current-page':          navigationComponentSourceMap.breadcrumbCurrent,
  'components-navigation-breadcrumb--default':               extractCode(BreadcrumbStories.Default),
  'components-navigation-breadcrumb--deep':                  extractCode(BreadcrumbStories.Deep),
  'components-navigation-breadcrumb--collapsed':             extractCode(BreadcrumbStories.Collapsed),
  'components-navigation-breadcrumb--minimal':               extractCode(BreadcrumbStories.Minimal),
  'components-navigation-breadcrumb--long-labels':           extractCode(BreadcrumbStories.LongLabels),
  'components-divider--horizontal':               navigationComponentSourceMap.dividerHorizontal,
  'components-divider--vertical':                 navigationComponentSourceMap.dividerVertical,
  'components-divider--inset':                    navigationComponentSourceMap.dividerInset,
  'components-pagination--basic':                 navigationComponentSourceMap.paginationBasic,
  'components-pagination--with-input':            navigationComponentSourceMap.paginationWithInput,
  'components-pagination--compact':               navigationComponentSourceMap.paginationCompact,
  'components-indicator--basic':                  navigationComponentSourceMap.indicatorBasic,
  'components-indicator--size':                   navigationComponentSourceMap.indicatorSize,
  'components-indicator--carousel':               navigationComponentSourceMap.indicatorCarousel,
  'components-indicator--interactive':            navigationComponentSourceMap.indicatorInteractive,
  'components-indicator--disabled':               navigationComponentSourceMap.indicatorDisabled,
  'components-side-navigation--basic':            navigationComponentSourceMap.sideNavigationBasic,
  'components-side-navigation--collapsed':        navigationComponentSourceMap.sideNavigationCollapsed,
  'components-side-navigation--subnav':           navigationComponentSourceMap.sideNavigationSubnav,
  'components-navigation-sidenavigation--expanded':          `<SideNavigation profileName="SOLUM" profileLogo={<SolumLogo />} defaultActiveId="users-list" items={sampleItems} />`,
  'components-navigation-sidenavigation--expanded-flat':     `<SideNavigation profileName="SOLUM" profileLogo={<SolumLogo />} defaultActiveId="dashboard" items={flatItems} />`,
  'components-navigation-sidenavigation--collapsed':         `<SideNavigation profileName="SOLUM" profileLogo={<SolumLogo />} defaultActiveId="users-list" defaultCollapsed items={sampleItems} />`,
  'components-navigation-sidenavigation--with-disabled':     `<SideNavigation profileName="SOLUM" profileLogo={<SolumLogo />} defaultActiveId="dashboard" items={itemsWithDisabled} />`,
  'components-navigation-sidenavigation--multiple-groups':   `<SideNavigation profileName="SOLUM" profileLogo={<SolumLogo />} defaultActiveId="data-ingestion" items={sampleItems} />`,
  'components-progress-stepper--basic':           navigationComponentSourceMap.progressStepperBasic,
  'components-progress-stepper--completed':       navigationComponentSourceMap.progressStepperCompleted,
  'components-progress-stepper--error':           navigationComponentSourceMap.progressStepperError,
  'components-progress-stepper--multi-step':      navigationComponentSourceMap.progressStepperMultiStep,
  'components-tab--basic':                        navigationComponentSourceMap.tabBasic,
  'components-tab--with-count':                   navigationComponentSourceMap.tabWithCount,
  'components-tab--horizontal-padding':           navigationComponentSourceMap.tabHorizontalPadding,
  'components-tab--with-section-title':           navigationComponentSourceMap.tabSectionTitle,
  'components-tab--disabled':                     navigationComponentSourceMap.tabDisabled,
  'components-navigation-tabs--size-md':                     `<Tabs size="md" defaultIndex={0} items={items} />`,
  'components-navigation-tabs--size-sm':                     `<Tabs size="sm" defaultIndex={0} items={items} />`,
  'components-navigation-tabs--with-disabled':               `<Tabs size="md" defaultIndex={0} items={[{label: 'Tab 1'}, {label: 'Tab 2'}, {label: 'Tab 3', disabled: true}]} />`,
  'components-navigation-tabs--disabled-selected':           `<Tabs size="md" defaultIndex={1} items={[{label: 'Tab 1'}, {label: 'Tab 2', disabled: true}, {label: 'Tab 3'}]} />`,
  'components-navigation-tabs--with-badge':                  `<Tabs size="md" defaultIndex={0} items={[{label: 'All', badge: 12}, {label: 'Active', badge: 5}]} />`,
  'components-navigation-tabs--with-dot':                    `<Tabs size="md" defaultIndex={0} items={[{label: 'Inbox', dot: true}, {label: 'Sent'}]} />`,
  'components-navigation-tabs--mixed':                       `<Tabs size="md" defaultIndex={1} items={[{label: 'Overview'}, {label: 'Issues', badge: 8, dot: true}, {label: 'Settings', disabled: true}]} />`,
  'components-navigation-tabs--sm-with-badge':               `<Tabs size="sm" defaultIndex={0} items={[{label: 'All', badge: 12}, {label: 'Active', badge: 5}, {label: 'Closed', badge: 0, disabled: true}]} />`,
  'components-toast-message--basic':              feedbackComponentSourceMap.basicToast,
  'components-toast-message--with-description':   feedbackComponentSourceMap.toastDescription,
  'components-toast-message--with-action':        feedbackComponentSourceMap.toastAction,
  'components-toast-message--with-progress':      feedbackComponentSourceMap.toastProgress,
  'components-toast-message--success':            feedbackComponentSourceMap.toastSuccess,
  'components-toast-message--error':              feedbackComponentSourceMap.toastError,
  'components-section-message--basic':            feedbackComponentSourceMap.sectionBasic,
  'components-section-message--with-description': feedbackComponentSourceMap.sectionDescription,
  'components-section-message--with-link':        feedbackComponentSourceMap.sectionLink,
  'components-section-message--with-dismiss':     feedbackComponentSourceMap.sectionDismiss,
  'components-section-message--error':            feedbackComponentSourceMap.sectionError,
  'components-section-message--success':          feedbackComponentSourceMap.sectionSuccess,
  'components-feedback-sectionmessage--neutral':           extractCode(SectionMessageStories.Neutral),
  'components-feedback-sectionmessage--info':              extractCode(SectionMessageStories.Info),
  'components-feedback-sectionmessage--success':           extractCode(SectionMessageStories.Success),
  'components-feedback-sectionmessage--warning':           extractCode(SectionMessageStories.Warning),
  'components-feedback-sectionmessage--error':             extractCode(SectionMessageStories.Error),
  'components-feedback-sectionmessage--brand-light':       extractCode(SectionMessageStories.BrandLight),
  'components-feedback-sectionmessage--without-actions':   extractCode(SectionMessageStories.WithoutActions),
  'components-feedback-sectionmessage--all-statuses':      extractCode(SectionMessageStories.AllStatuses),
  'components-feedback-banner--basic':                     feedbackComponentSourceMap.bannerBasic,
  'components-feedback-banner--error':                     feedbackComponentSourceMap.bannerError,
  'components-feedback-banner--warning':                   feedbackComponentSourceMap.bannerWarning,
  'components-feedback-banner--announcement':              feedbackComponentSourceMap.bannerAnnouncement,
  'components-feedback-banner--with-link':                 feedbackComponentSourceMap.bannerLink,
  'components-feedback-banner--dismissible':               feedbackComponentSourceMap.bannerDismissible,
  'components-feedback-banner--brand':                     extractCode(BannerStories.Brand),
  'components-feedback-banner--without-action':            extractCode(BannerStories.WithoutAction),
  'components-feedback-banner--all-colors':                extractCode(BannerStories.AllColors),
  'components-text-input--basic':                 inputComponentSourceMap.basicTextInput,
  'components-text-input--with-helper':           inputComponentSourceMap.textInputHelper,
  'components-text-input--required':              inputComponentSourceMap.requiredTextInput,
  'components-text-input--leading':               inputComponentSourceMap.textInputLeading,
  'components-text-input--trailing-button':       inputComponentSourceMap.textInputTrailing,
  'components-text-input--error':                 inputComponentSourceMap.textInputError,
  'components-text-input--disabled':              inputComponentSourceMap.textInputDisabled,
  'components-text-area--basic':                  inputComponentSourceMap.basicTextArea,
  'components-text-area--with-helper':            inputComponentSourceMap.textAreaHelper,
  'components-text-area--with-counter':           inputComponentSourceMap.textAreaCounter,
  'components-text-area--with-action':            inputComponentSourceMap.textAreaAction,
  'components-text-area--with-copy':              inputComponentSourceMap.textAreaCopy,
  'components-text-area--resizable':              inputComponentSourceMap.textAreaResizable,
  'components-text-area--error':                  inputComponentSourceMap.textAreaError,
  'components-text-area--disabled':               inputComponentSourceMap.textAreaDisabled,
  'components-text-area--read-only':              inputComponentSourceMap.textAreaReadOnly,
  'components-loading-progressbar--small':               extractCode(ProgressBarStories.Small),
  'components-loading-progressbar--medium':              extractCode(ProgressBarStories.Medium),
  'components-loading-progressbar--states':              extractCode(ProgressBarStories.States),
  'components-loading-progressbar--no-label':            extractCode(ProgressBarStories.NoLabel),
  'components-loading-progressbar--no-value':            extractCode(ProgressBarStories.NoValue),
  'components-loading-progressbar--table-sizes':         extractCode(ProgressBarStories.TableSizes),
  'components-loading-progressbar--table-with-number':   extractCode(ProgressBarStories.TableWithNumber),
  'components-loading-progressbar--table-values':        extractCode(ProgressBarStories.TableValues),
  'components-loading-spinner--below-sm':                 extractCode(SpinnerStories.BelowSm),
  'components-loading-spinner--below-md':                 extractCode(SpinnerStories.BelowMd),
  'components-loading-spinner--below-lg':                 extractCode(SpinnerStories.BelowLg),
  'components-loading-spinner--right-sm':                 extractCode(SpinnerStories.RightSm),
  'components-loading-spinner--right-md':                 extractCode(SpinnerStories.RightMd),
  'components-loading-spinner--right-lg':                 extractCode(SpinnerStories.RightLg),
  'components-loading-spinner--sizes':                    extractCode(SpinnerStories.Sizes),
  'components-loading-spinner--inverse':                  extractCode(SpinnerStories.Inverse),
  'components-loading-spinner--no-label':                 extractCode(SpinnerStories.NoLabel),
  'components-loading-skeleton--items':                   extractCode(SkeletonStories.Items),
  'components-loading-skeleton--card':                    extractCode(SkeletonStories.Card),
  'components-loading-skeleton--text':                    extractCode(SkeletonStories.Text),
  'components-loading-skeleton--list':                    extractCode(SkeletonStories.List),
  'components-select-select--basic':                     selectionComponentSourceMap.basicSelect,
  'components-select-select--label-helper':              selectionComponentSourceMap.selectLabelHelper,
  'components-select-select--text':                      selectionComponentSourceMap.textSelect,
  'components-select-select--single-states':             selectionComponentSourceMap.singleSelectStates,
  'components-select-select--multi':                     selectionComponentSourceMap.multiSelect,
  'components-select-select--multi-states':              selectionComponentSourceMap.multiSelectStates,
  'components-select-select--counter':                   selectionComponentSourceMap.selectCounter,
  'components-select-select--placeholder':               extractCode(SelectStories.Placeholder) || `<Select options={basicOptions} label="Label" placeholder="placeholder" />`,
  'components-select-select--done':                      extractCode(SelectStories.Done) || `<Select options={basicOptions} label="Label" defaultValue="opt1" />`,
  'components-select-select--error':                     extractCode(SelectStories.Error) || `<Select options={basicOptions} label="Label" defaultValue="opt1" state="error" helperText="Helper text" />`,
  'components-select-select--disabled':                  extractCode(SelectStories.Disabled) || `<Select options={basicOptions} label="Label" defaultValue="opt1" state="disabled" />`,
  'components-select-select--readonly':                  extractCode(SelectStories.Readonly) || `<Select options={basicOptions} label="Label" defaultValue="opt1" state="readonly" />`,
  'components-select-select--with-helper-text':          extractCode(SelectStories.WithHelperText) || `<Select options={basicOptions} label="Label" helperText="Helper text" />`,
  'components-select-select--required':                  extractCode(SelectStories.Required) || `<Select options={basicOptions} label="Label" required placeholder="Select an option" />`,
  'components-select-select--all-states':                `<Select options={basicOptions} label="Label" state="default" />
<Select options={basicOptions} label="Label" state="error" helperText="Helper text" />
<Select options={basicOptions} label="Label" state="disabled" />
<Select options={basicOptions} label="Label" state="readonly" />`,
  'components-select-select--multi-placeholder':         `<MultiSelect options={basicOptions} label="Label" placeholder="placeholder" />`,
  'components-select-select--multi-done':                `<MultiSelect options={basicOptions} label="Label" defaultValue={['opt1', 'opt2', 'opt3']} />`,
  'components-select-select--multi-error':               `<MultiSelect options={basicOptions} label="Label" defaultValue={['opt1', 'opt2']} state="error" helperText="Helper text" />`,
  'components-select-select--multi-disabled':            `<MultiSelect options={basicOptions} label="Label" defaultValue={['opt1', 'opt2', 'opt3']} state="disabled" />`,
  'components-select-select--all-multi-states':          `<MultiSelect options={basicOptions} label="Label" state="default" />
<MultiSelect options={basicOptions} label="Label" state="error" helperText="Helper text" />
<MultiSelect options={basicOptions} label="Label" state="disabled" />
<MultiSelect options={basicOptions} label="Label" state="readonly" />`,
  'components-select-select--with-long-options':         `<Select options={countryOptions} label="Country" placeholder="Select a country" helperText="Choose your country of residence" />`,
  'components-select-select--sm-vs-md':                  `<Select options={basicOptions} label="Label" placeholder="placeholder" size="sm" />
<Select options={basicOptions} label="Label" placeholder="placeholder" size="md" />`,
  'components-status-indicator-badge--basic':                      statusIndicatorSourceMap.badgeBasic,
  'components-status-indicator-badge--with-icon':                  statusIndicatorSourceMap.badgeIcon,
  'components-status-indicator-badge--color':                      statusIndicatorSourceMap.badgeColor,
  'components-badge-counter--basic':              statusIndicatorSourceMap.counterBasic,
  'components-badge-counter--size':               statusIndicatorSourceMap.counterSize,
  'components-badge-counter--grey':               statusIndicatorSourceMap.counterGrey,
  'components-badge-status--number':              statusIndicatorSourceMap.statusNumber,
  'components-badge-status--dot':                 statusIndicatorSourceMap.statusDot,
  'components-badge-status--new':                 statusIndicatorSourceMap.statusNew,
  'components-status-indicator-chip--basic':                       statusIndicatorSourceMap.chipBasic,
  'components-status-indicator-chip--size':                        statusIndicatorSourceMap.chipSize,
  'components-status-indicator-chip--state':                       statusIndicatorSourceMap.chipState,
  'components-status-indicator-chip--sm-selected':                 extractCode(ChipStories.SmSelected),
  'components-status-indicator-chip--sm-default':                  extractCode(ChipStories.SmDefault),
  'components-status-indicator-chip--md-selected':                 extractCode(ChipStories.MdSelected),
  'components-status-indicator-chip--md-default':                  extractCode(ChipStories.MdDefault),
  'components-status-indicator-chip--all-variants':                extractCode(ChipStories.AllVariants),
  'components-status-indicator-chip--icon-variants':               extractCode(ChipStories.IconVariants),
  'foundation-icon--icon-sizes':                  extractCode(IconStories.IconSizes),
  'foundation-icon--with-custom-icon':            extractCode(IconStories.WithCustomIcon),
  'components-dropdown-dropdownitem--default':             extractCode(DropdownItemStories.Default),
  'components-dropdown-dropdownitem--selected':            extractCode(DropdownItemStories.Selected),
  'components-dropdown-dropdownitem--focused':             extractCode(DropdownItemStories.Focused),
  'components-dropdown-dropdownitem--disabled':            extractCode(DropdownItemStories.Disabled),
  'components-dropdown-dropdownitem--radio':               extractCode(DropdownItemStories.Radio),
  'components-dropdown-dropdownitem--checkbox':            extractCode(DropdownItemStories.Checkbox),
  'components-dropdown-dropdownitem--all-variants':        extractCode(DropdownItemStories.AllVariants),
  'components-input-texthelper--default':               extractCode(TextHelperStories.Default),
  'components-input-texthelper--error':                 extractCode(TextHelperStories.Error),
  'components-input-texthelper--all-variants':          extractCode(TextHelperStories.AllVariants),
  'components-input-textlabel--md':                     extractCode(TextLabelStories.Md),
  'components-input-textlabel--md-required':            extractCode(TextLabelStories.MdRequired),
  'components-input-textlabel--sm':                     extractCode(TextLabelStories.Sm),
  'components-input-textlabel--sm-required':            extractCode(TextLabelStories.SmRequired),
  'components-input-textlabel--all-variants':           extractCode(TextLabelStories.AllVariants),
  'components-empty-state--basic':                statusIndicatorSourceMap.emptyBasic,
  'components-empty-state--search':               statusIndicatorSourceMap.emptySearch,
  'components-structured-list--basic':            structuredListComponentSourceMap.basic,
  'components-structured-list--checkbox':         structuredListComponentSourceMap.checkbox,
  'components-structured-list--status':           structuredListComponentSourceMap.status,
  'components-structured-list--action':           structuredListComponentSourceMap.action,
  'components-structured-list--horizontal':       structuredListComponentSourceMap.horizontal,
  'components-structured-list--vertical':         structuredListComponentSourceMap.vertical,
  'components-structured-list--overflow':         structuredListComponentSourceMap.overflow,
  'components-structured-list--selection':        structuredListComponentSourceMap.selection,
  'components-structured-list-structuredlist--vertical':          extractCode(StructuredListStories.Vertical),
  'components-structured-list-structuredlist--vertical-no-divider': extractCode(StructuredListStories.VerticalNoDivider),
  'components-structured-list-structuredlist--horizontal':        extractCode(StructuredListStories.Horizontal),
  'components-structured-list-structuredlist--horizontal-no-divider': extractCode(StructuredListStories.HorizontalNoDivider),
  'components-color-picker--basic':               pickerComponentSourceMap.basicColorPicker,
  'components-color-picker--with-label':          pickerComponentSourceMap.colorPickerLabel,
  'components-color-picker--with-input':          pickerComponentSourceMap.colorPickerInput,
  'components-color-picker--multi-row':           pickerComponentSourceMap.colorPickerMultiRow,
  'components-color-picker--disabled':            pickerComponentSourceMap.colorPickerDisabled,
  'components-date-range-picker--basic':          pickerComponentSourceMap.basicDateRange,
  'components-date-range-picker--quick-select':   pickerComponentSourceMap.dateRangeQuick,
  'components-date-range-picker--time-input':     pickerComponentSourceMap.dateRangeTime,
  'components-date-range-picker--footer-actions': pickerComponentSourceMap.dateRangeFooter,
  'components-date-single-picker--basic':          pickerComponentSourceMap.basicDateSingle,
  'components-date-single-picker--selection-panel': pickerComponentSourceMap.dateSingleSelectionPanel,
  'components-date-single-picker--footer':         pickerComponentSourceMap.dateSingleFooter,
  'components-date-single-picker--disabled-date':  pickerComponentSourceMap.disabledDateSingle,
  'components-date-single-picker--in-form':        pickerComponentSourceMap.dateSingleInForm,
  'components-time-picker--basic':                 pickerComponentSourceMap.basicTime,
  'components-time-picker--24-hour':               pickerComponentSourceMap.time24Hour,
  'components-time-picker--seconds':               pickerComponentSourceMap.timeSeconds,
  'components-time-picker--without-footer':        pickerComponentSourceMap.timeWithoutFooter,
  'components-time-picker--with-date-picker':      pickerComponentSourceMap.timeWithDatePicker,
  'components-menu--basic':                        menuSourceMap.basic,
  'components-menu--cascading':                    menuSourceMap.cascading,
  'components-menu--icon-trigger':                 menuSourceMap.iconTrigger,
  'components-menu--select-trigger':               menuSourceMap.selectTrigger,
  'components-upload--basic':                      uploadSourceMap.basic,
  'components-upload--drag':                       uploadSourceMap.drag,
  'components-upload--uploading':                  uploadSourceMap.uploading,
  'components-upload--error':                      uploadSourceMap.error,
};
